---
- name: Deploy game roms
  ansible.builtin.copy:
    src: "{{ retropi_roms_source_location }}"
    dest: "{{ retropi_roms_target_location }}"
    owner: "{{ retropi_roms_user }}"
    group: "{{ retropi_roms_user }}"
    mode: "0644"
  become: true
  become_user: "{{ retropi_roms_user }}"
