---

- name: deploy game roms
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ retropi_roms_location }}"
    owner: "{{ retropi_user }}"
    group: "{{ retropi_user }}"
    mode: 0644
  loop:
    - nes
    - snes
