---
- name: Deploy game roms
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/retropi_roms/"
    dest: "{{ retropi_roms_location }}"
    owner: "{{ retropi_roms_user }}"
    group: "{{ retropi_roms_user }}"
    mode: "0644"
  become: true
  become_user: "{{ retropi_roms_user }}"
